### ISSUE TITLE
sharing libs not working

### ISSUE THREAD

**Issue by rarmatei** [manfredsteyer/module-federation-plugin-example-nx#1]
First of all, thank you so much for everything you're doing to bring Module Federation to the Angular/Nx space. The experience of using `@angular-architects/module-federation` in Nx workspaces has been incredibly straightforward!

I was wondering if you were able to add Nx `libs/` to the `shared: [...]` array of the federation plugin?

For me, when I try to add a lib to the shared array I get this:

```bash
Error: Module not found: Error: Can't resolve '@mfe1/test' in '[...]/module-federation-plugin-example-nx/apps/mfe1/src/app/flights/flights-search'
```

**Comment by manfredsteyer** [comment]
Just one idea: When we do incremental compilation (nx build --with-deps) the libs are compiled individually into the dist folder (or copied from the cache). In this case, we could try to point there. I think, there is a webpack setting to define alternatives to the node_modules folder or perhaps we use sym links to link dist/libs/my-lib to node_modules/my-lib (like lerna)

Does this help?

**Comment by rarmatei** [comment]
Thank you for the response 🙌 

I managed to get it working by explicitly adding the `tsconfig-paths-webpack-plugin` to webpack config:
https://github.com/rarmatei/module-federation-nx-libs-example/commit/a96b62bb1f63f58afd5e9520b2fd8e7142c18e67

It works great - the module is instantiated only once, as expected.

I would love to submit a PR to `@angular-architects/module-federation` if you think this might be a helpful configuration option (especially for Nx projects). 

One thing I'm not sure about though - is how come the webpack bundling works and you can import from local path mappings when not using the federation plugin - but when you add the lib to the shared federation plugin array, webpack doesn't recognise it anymore? Maybe I'm just asking the wrong question 😄

**Comment by smasala** [comment]
This problem is back again.... :(

```
"@angular-architects/module-federation": "12.5.0",
"@angular/common": "12.2.12",
"@nrwl/angular": "13.1.4",
```

If the libraries are buildable then you get the following error if you try and share them or expose a module

```
./libs/my-shared-lib/src/index.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: /Users/bob/git/mynxrepo/libs/my-shared-lib/src/index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at /Users/bob/git/mynxrepo/node_modules/@ngtools/webpack/src/ivy/loader.js:59:26
    ```

**Comment by smasala** [comment]
If the libraries are buildable then you get the following error if you try and share them too:
```
./libs/my-shared-lib/src/index.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: /Users/bob/git/mynxrepo/libs/my-shared-lib/src/index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at /Users/bob/git/mynxrepo/node_modules/@ngtools/webpack/src/ivy/loader.js:59:26
    ```

**Comment by smasala** [comment]
More information https://github.com/nrwl/nx/issues/6923#issuecomment-968098438

**Comment by smasala** [comment]
It downloaded `@angular-architects/module-federation` 12.5.0 and not 12.5.3 🤦‍♂️

**Comment by Nxtivision** [comment]
> Thank you for the response 🙌
> 
> I managed to get it working by explicitly adding the `tsconfig-paths-webpack-plugin` to webpack config: [rarmatei/module-federation-nx-libs-example@a96b62b](https://github.com/rarmatei/module-federation-nx-libs-example/commit/a96b62bb1f63f58afd5e9520b2fd8e7142c18e67)
> 
> It works great - the module is instantiated only once, as expected.
> 
> I would love to submit a PR to `@angular-architects/module-federation` if you think this might be a helpful configuration option (especially for Nx projects).
> 
> One thing I'm not sure about though - is how come the webpack bundling works and you can import from local path mappings when not using the federation plugin - but when you add the lib to the shared federation plugin array, webpack doesn't recognise it anymore? Maybe I'm just asking the wrong question 😄

@rarmatei It seems your workaround still work in 2023... 😄 And we aren't in a Nx project!
